"""The AI Committee as a gate on a trade the rules already approved.

The rules scan and score every symbol with no AI. Only a plan that passed them, in a market that is
open, that would open automatically (auto-execute on and a free slot) or that you generated by hand,
goes to the committee, which is handed all the data the app has gathered. Its rating is then read as a
yes or a no:

    long  : Buy / Overweight agree; Hold / Underweight / Sell object
    short : Sell / Underweight agree; Hold / Overweight / Buy object

An objection can only STOP the trade ("cancel": the plan becomes a no-trade, "hold": it stays pending
for a person). It can never start a trade, change a direction, an entry, a stop or a size, so the
boundary every other AI input in this app has is unchanged. A committee that cannot run or cannot be
read (no provider, a failed step, an unreadable rating) records no objection and says so: nothing is
invented in either direction.

Cost is bounded twice: one run is capped by `committee_max_llm_calls`, and one scan by a
`CommitteeGateBudget` of at most `committee_gate_max_per_scan` runs, and a manual Generate click is given a budget of one. A caller that
passes no budget (a backtest) never runs the gate.
"""

from __future__ import annotations

import json
import logging
from dataclasses import asdict, dataclass

from sqlmodel import Session

from app.committee.models import RUN_DONE, RUN_FAILED, RUN_RUNNING, CommitteeRun
from app.committee.orchestrator import clamp_rounds, planned_steps, run_committee
from app.config import AppSettings
from app.data_providers.base import AllProvidersFailedError, DataProvider
from app.llm_providers.base import LLMProvider
from app.timeutil import utcnow_naive

logger = logging.getLogger(__name__)

BULLISH_RATINGS = frozenset({"Buy", "Overweight"})
BEARISH_RATINGS = frozenset({"Sell", "Underweight"})


@dataclass
class CommitteeGateBudget:
    """How many committee runs one scan may still spend.

    `background` is for a plan a person is waiting on: the run is started in the background and the plan is
    returned at once (services/committee_gate_service.py), instead of the pass waiting for the result.
    `manager` and `session_factory` default to the app's own; tests pass theirs."""

    remaining: int
    background: bool = False
    manager: object | None = None
    session_factory: object | None = None

    def take(self) -> bool:
        if self.remaining <= 0:
            return False
        self.remaining -= 1
        return True


@dataclass(frozen=True)
class GateResult:
    ran: bool
    objects: bool
    rating: str | None
    run_id: int | None
    note: str  # one plain sentence for the plan card


def agrees_with(rating: str | None, direction: str) -> bool | None:
    """True/False: does the rating back this direction. None: no rating to judge."""
    if rating is None:
        return None
    backing = BULLISH_RATINGS if direction == "long" else BEARISH_RATINGS
    return rating in backing


def outcome_fields(outcome) -> dict:
    """The CommitteeRun columns an outcome fills (shared with the background runner's wording)."""
    return {
        "status": RUN_FAILED if outcome.error else RUN_DONE,
        "finished_at": utcnow_naive(),
        "steps": json.dumps([asdict(s) for s in outcome.steps]),
        "llm_calls_used": outcome.calls_used,
        "rating": outcome.rating,
        "rating_summary": outcome.summary,
        "rating_key_risks": outcome.key_risks,
        "rating_conviction": outcome.conviction,
        "rating_parse": outcome.parse,
        "web_search": outcome.web_search_used,
        "error": outcome.error,
    }


def gate_is_usable(settings: AppSettings, llm: LLMProvider) -> bool:
    return bool(settings.committee_gate_enabled) and llm.name != "none" and llm.is_configured()


def run_committee_gate(
    session: Session,
    symbol: str,
    direction: str,
    data_provider: DataProvider,
    llm: LLMProvider,
    settings: AppSettings,
) -> GateResult:
    """Run the committee for `symbol` now, store the run, and say whether it objects to `direction`.
    Never raises: any failure is a result with ran=False or no rating, and no objection."""
    run = CommitteeRun(
        symbol=symbol,
        status=RUN_RUNNING,
        steps=json.dumps([asdict(s) for s in planned_steps(settings.committee_debate_rounds, settings.committee_risk_rounds)]),
        llm_calls_max=settings.committee_max_llm_calls,
        debate_rounds=clamp_rounds(settings.committee_debate_rounds),
        risk_rounds=clamp_rounds(settings.committee_risk_rounds),
        provider=llm.name,
    )
    try:
        session.add(run)
        session.commit()
        session.refresh(run)
        run_id = run.id

        def publish(steps: list[dict], calls: int) -> None:
            # Saved after every step, so the AI Committee page shows this run live like a button-started one.
            run.steps = json.dumps(steps)
            run.llm_calls_used = calls
            session.add(run)
            session.commit()

        outcome = run_committee(symbol, data_provider, llm, settings, publish, session=session)
    except AllProvidersFailedError:
        _fail(session, run, f"No price data could be fetched for {symbol}.")
        return GateResult(False, False, None, getattr(run, "id", None), "AI Committee could not run: no price data.")
    except Exception as exc:  # the gate must never break plan generation
        logger.exception("committee gate failed for %s", symbol)
        session.rollback()
        _fail(session, run, f"Unexpected error: {str(exc)[:200]}")
        return GateResult(False, False, None, getattr(run, "id", None), "AI Committee could not run (an error was logged).")

    for key, value in outcome_fields(outcome).items():
        setattr(run, key, value)
    session.add(run)
    session.commit()

    rating = outcome.rating
    verdict = agrees_with(rating, direction)
    if verdict is None:
        return GateResult(True, False, None, run_id, f"AI Committee gave no readable rating (run #{run_id}), so it neither approved nor objected.")
    if verdict:
        return GateResult(True, False, rating, run_id, f"AI Committee rated {symbol} {rating} (run #{run_id}), which backs the {direction}.")
    return GateResult(
        True, True, rating, run_id, f"AI Committee rated {symbol} {rating} (run #{run_id}), which does not back a {direction}."
    )


def _fail(session: Session, run: CommitteeRun, message: str) -> None:
    try:
        run.status, run.error, run.finished_at = RUN_FAILED, message, utcnow_naive()
        session.add(run)
        session.commit()
    except Exception:  # noqa: BLE001 - recording the failure is best effort
        session.rollback()
        logger.exception("committee gate: could not record the failure")
