from __future__ import annotations

import logging
import secrets

from fastapi import Header, HTTPException, Request

from app.auth import SESSION_COOKIE_NAME, verify_session_token
from app.config import AppSettings, get_infra_settings, load_app_settings
from app.data_providers.base import DataProvider
from app.data_providers.factory import get_data_provider as _build_data_provider
from app.llm_providers.base import LLMProvider
from app.llm_providers.factory import get_llm_provider as _build_llm_provider

# Re-exported so routers only import from app.api.deps
from app.database import get_session  # noqa: F401

logger = logging.getLogger(__name__)


def get_app_settings() -> AppSettings:
    return load_app_settings()


def require_auth(request: Request, x_api_key: str | None = Header(default=None)) -> None:
    """Auth gate in front of every router. Two independent ways in, either
    is sufficient:
    - a session cookie from a successful POST /api/auth/login (the
      dashboard's own login screen — see app/auth.py and
      api/routers/auth.py) — this is what the bundled frontend actually
      uses now;
    - a matching X-API-Key header (InfraSettings.api_shared_secret) — kept
      for programmatic/script access (Swagger UI, curl, a cron job) that
      has no browser to hold a cookie in.

    Both secrets are auto-generated by default now (config.py's
    _load_or_create_shared_secret / _load_or_create_auth_password); the
    only no-op case is the explicit ALLOW_UNAUTHENTICATED_API opt-out,
    which is also what /api/auth/status reads to tell the frontend not to
    show a login screen at all in that mode.
    """
    infra = get_infra_settings()
    if infra.allow_unauthenticated_api:
        return

    if x_api_key and infra.api_shared_secret:
        # compare_digest, not ==: a plain string comparison short-circuits
        # on the first differing byte, so response timing leaks a correct
        # prefix and the secret can be recovered byte by byte.
        if secrets.compare_digest(x_api_key, infra.api_shared_secret):
            return

    if verify_session_token(request.cookies.get(SESSION_COOKIE_NAME), infra):
        return

    # Client host, never the submitted key — logging someone's wrong guess
    # verbatim would put credential-shaped material in a log file for no
    # benefit, and a real match already returned above in both branches.
    # This is the one signal an operator has of a brute-force attempt
    # against a VPS deploy short of parsing access logs themselves.
    client = request.client.host if request.client else "unknown"
    logger.warning("Rejected request to %s from %s: not logged in and no valid X-API-Key", request.url.path, client)
    raise HTTPException(status_code=401, detail="Not authenticated")


def get_data_provider() -> DataProvider:
    return _build_data_provider(load_app_settings())


def get_llm_provider() -> LLMProvider:
    return _build_llm_provider(load_app_settings())
